drone/drone-kaniko

cmd/kaniko-docker/main.go
docker/docker/Dockerfile.linux.amd64
docker/docker/Dockerfile.linux.arm64
docker/ecr/Dockerfile.linux.amd64
docker/ecr/Dockerfile.linux.arm64
docker/gcr/Dockerfile.linux.amd64
docker/gcr/Dockerfile.linux.arm64

Updated base version of kaniko image from debug-v0.19.0 to v1.3.0
kaniko version for arm arch was not present for v0.19.0.

Updated kaniko base image to v1.3.0

---

README.md
cmd/kaniko-docker/main.go

Docker v2 registry is not supported in kaniko. Hence using v1 registry instead if user passes v2 registry.

fix docker v2 registry issue

---

cmd/kaniko-gcr/main.go
docker/docker/Dockerfile.linux.amd64
docker/ecr/Dockerfile.linux.amd64
docker/gcr/Dockerfile.linux.amd64

Fixed kaniko image to v1.3.0 from amd-v1.3.0.
amd-v1.3.0 does not have docker-credential-gcr which is required for uploading to gcr.

Fix kaniko-gcr docker file

---

cmd/kaniko-docker/main.go
kaniko.go

Added a new flag to skip https certificate verification for private docker registries.

add skip-tls-verify flag for insecure private registries

---

cmd/kaniko-ecr/main.go
docker/docker/Dockerfile.linux.amd64
docker/docker/Dockerfile.linux.arm64
docker/ecr/Dockerfile.linux.amd64
docker/ecr/Dockerfile.linux.arm64
docker/gcr/Dockerfile.linux.amd64
docker/gcr/Dockerfile.linux.arm64

Add support for public ecr: [amazon-ecr-credential](https://github.com/awslabs/amazon-ecr-credential-helper#docker)
```json
{
"credHelpers": {
"public.ecr.aws": "ecr-login",
"<aws_account_id>.dkr.ecr.<region>.amazonaws.com": "ecr-login"
}
}
```
[https://aws.amazon.com/blogs/containers/amazon-ecr-credential-helper-now-supports-amazon-ecr-public/](https://aws.amazon.com/blogs/containers/amazon-ecr-credential-helper-now-supports-amazon-ecr-public/)
@shubham149 what do you think about this change?

add support for public ecr

---

cmd/kaniko-docker/main.go
cmd/kaniko-ecr/main.go
cmd/kaniko-gcr/main.go
kaniko.go

This updates all binaries and the plugin to skip authentication mechanisms when `no_push: true`. This allows pipelines to perform builds without requiring secrets, which can be useful during `pull_request` events, for example.
This was tested with the following public image
```
---
kind: pipeline
name: default
steps:
- name: publish
image: colinhoglund/kaniko-ecr
settings:
no_push: true
```
There is also a commit with a bit of linting.

Do not require username/password with `no_push: true`

---

cmd/kaniko-ecr/main.go
cmd/kaniko-ecr/main_test.go
pkg/docker/config.go
pkg/docker/config_test.go
pkg/docker/constants.go

This adds support for docker credentials to be passed to the `kaniko-ecr` plugin to avoid hitting rate limits when pulling from docker hub. Configuration is setup similar to https://github.com/drone-plugins/drone-docker.
This also removes the `"credStore": "ecr-login"` configuration, which seems to be a typo for `credsStore` and is also unnecessary with the `credHelpers` configuration.
A compiled version of this has been pushed to `colinhoglund/kaniko-ecr:docker-pass`

Support Docker Hub credentials when pulling with kaniko-ecr

---

cmd/kaniko-docker/main.go
cmd/kaniko-docker/main_test.go

I noticed this when trying to do a bulk change of our repositories to use the upstreaam `plugins/kaniko{,-ecr,-gcr}` -- they don't behave the same when you pass
```
settings:
registry: example.com
repo: bar
```
Specifically:
* kaniko will try `index.docker.io/bar`
* kaniko-ecr and -gcr will try `example.com/bar` (which is the behavior I would expect)
So, with the current state, our non-ECR / non-GCR images have to repeat the registry in the settings block, and they are inconsistent with the internal one.
This PR allows use of either the "compatible" setting block like
```
settings:
registry: example.com
repo: bar
```
or the previously required
```
settings:
registry: example.com
repo: example.com/bar
```
with the same results of trying to push to `example.com/bar`
This change attempts to …

Unify registry+repo behavior between plugins

---

kaniko.go

[Google Cloud document: Using Kaniko cache](https://cloud.google.com/build/docs/kaniko-cache#configuring_the_cache_expiration_time)
> The syntax is --cache-ttl=XXh where XX is time in hours. For example, --cache-ttl=6h sets the cache expiration to 6 hours. If you run builds using the gcloud builds submit --tag [IMAGE] command, the default value of the --cache-ttl flag is 6 hours. If you are using the Kaniko executor image directly, the default value is 2 weeks.

Fix "--cache-ttl" flag missing unit in duration

---

README.md
cmd/kaniko-docker/main.go
cmd/kaniko-ecr/main.go
cmd/kaniko-gcr/main.go
go.mod
go.sum
kaniko.go
kaniko_test.go
pkg/tagger/tagger.go
pkg/tagger/tagger_test.go

Support the feature in the ["Autotag" section](https://plugins.drone.io/drone-plugins/drone-docker/) of docker plugin.
The logic is forked from https://github.com/drone-plugins/drone-docker code base with necessary modification. I've tested it e2e for DockerHub on my Drone server via this plugin image https://hub.docker.com/repository/docker/15cm/drone-kaniko, for both tag pushes and commit pushes.
With this change the .drone.yml in this repo should work as intended.
Other changes:
- Rename the existing "auto tag" flags/code to "expand tag" for a less misleading naming.
- ATTENTION: make a breaking change to set default value of "--tags" to empty.
Rationale is to expect most users to use the auto tagging feature. When power users want to specify tags, they should always explicitly set …

Port the auto tag feature from docker plugin

---

cmd/kaniko-docker/main.go

Fixed assignment of Build.Repo and Build.CacheRepo so it not only contains the specified repo, but also registry by using buildRepo().
This required for pushing images to private repositories.

fix: Build.Repo and Build.CacheRepo now uses buildRepo()

---

.drone.yml
docker/docker/Dockerfile.linux.amd64.kaniko1.8.0
docker/docker/manifest-kaniko1.8.0.tmpl
docker/ecr/Dockerfile.linux.amd64.kaniko1.8.0
docker/ecr/manifest-kaniko1.8.0.tmpl
docker/gcr/Dockerfile.linux copy.amd64
docker/gcr/manifest-kaniko1.8.0.tmpl

Kaniko 1.6.0 will still remain the default version. With this change, it will publish an extra docker image of the plugin using kaniko version 1.8.0

Publish plugin with latest kaniko 1.8.0 image

---

cmd/kaniko-docker/main.go

When registry is the default official docker value, return repo only

Default registry value is not "" but v1RegistryURL

---

cmd/kaniko-docker/main.go
cmd/kaniko-docker/main_test.go

PR #40 added prepending of registry url to repo name. But there are some missing cases present:
1. If registry URL is public dockerhub, the full repo name: index.docker.io//: but this change generates repo name as https://index.docker.io/v1/<myrepo>/<myimage>:latest. Also, it needs to handle repo's without dockerhubUsr e.g. alpine image.
2. https:// is usually present in the registry url but should not be mentioned in the repo name.
3. Some registry url's include version number which should not be present in repo name.
Hence, this will make prepending of registry url to repo name optional by introducing a field expand_repo which is by default false.

Making prepend of registry url to repo name optional

---

.drone.yml
go.mod

The automation suite for drone-kaniko is passing successfully with the new updated images.
Reason for image update:
Security Reference Ticket - https://harness.atlassian.net/browse/SECAPP-258
To meet federal requirements for storing harness images.

golang image upgrade to 1.18

---

kaniko_test.go

We rely on this behavior, and so we added a test case to make sure it was working as we expected.
It seems worth contributing so that anyone else can easily check and see the behavior, and so that it never gets accidentally broken in the future.

Add beta testcase for clarity, coverage, and regression prevention

---

cmd/kaniko-ecr/main.go

The `assume-role` functionality does not currently work if you set `create_repository`, `lifecycle_policy` or `repository_policy`. This is because these 3 functions load the default config, and ignore the ARN passed via the `assume_role` parameter.
This PR addresses this issue (the role that is set via `assume_role` is also used for these 3 functions). Tested in Drone Kaniko builds and all working as expected. Thanks for looking

ECR: Add assume-role support for create-repository, *-policy

---

cmd/kaniko-acr/main.go

Adds validations to error out gracefully in case no elements exist in response.Value from the /subscriptions API response

add validations on response from /subscriptions API in ACR

---

kaniko.go

The kaniko flag `snapshotMode` is deprecated in favor of `snapshot-mode`. The default value of `snapshot-mode` is `full`. As a result, the `optimize` flag set in Harness CI's `BuildAndPushToDocker` steps doesn't behave as expected because the `full` mode triggers a full filesystem scan which is slow. The `optimize` flag in Harness translates to `snapshot-mode=redo` which means only filesystem deltas are compared which is much faster. 
This change fixes the flag name being sent to Kaniko executor. I verified that the executor present in the current version already supports this flag as shown below:
```
mantri@harness% docker run -it --entrypoint /kaniko/executor plugins/kaniko:1.8.10 --help | grep snapshot-mode
--snapshot-mode string                      Change the file attributes …
```

[CI-13182]: Use snapshot-mode instead of snapshotMode

---

docker/acr/Dockerfile.linux.amd64
docker/acr/Dockerfile.linux.arm64
docker/docker/Dockerfile.linux.amd64
docker/docker/Dockerfile.linux.arm64
docker/ecr/Dockerfile.linux.amd64
docker/ecr/Dockerfile.linux.arm64
docker/gar/Dockerfile.linux.amd64
docker/gar/Dockerfile.linux.arm64
docker/gcr/Dockerfile.linux.amd64

Upgrade Kaniko version that supports preserving permissions via the chmod argument on the Docker file.

upgrade kaniko version for chmod on ADD and COPY

---

kaniko.go
kaniko_test.go
pkg/output/output.go
pkg/output/output_test.go

IMAGE_TAR_PATH is now accessible via a output variable and can also be used in STO steps as expression - 
<+steps.STEP_ID.output.outputVariables.IMAGE_TAR_PATH>

feat:[CI-15236]: Added IMAGE_TAR_PATH as output variable for the plugin.

---

cmd/kaniko-acr/main.go
cmd/kaniko-docker/main.go
cmd/kaniko-ecr/main.go
cmd/kaniko-gar/main.go
cmd/kaniko-gcr/main.go
kaniko.go

new input `PLUGIN_IGNORE_PATHS` (a string slice) that allows users to specify multiple paths to ignore during the build. Each path is trimmed and appended as a separate `--ignore-path` flag when executing the Kaniko build process.

feat: [CI-16193]: Support multiple ignore paths

---

cmd/kaniko-acr/main.go

This update refines the setupAuth function in the drone-kaniko plugin to improve backward compatibility and clarify error handling for NO_PUSH mode.
- Error Handling: When `NO_PUSH` is enabled, if fetching the ACR token or creating the Docker config fails, the function now logs a warning (prefixed with `“NO_PUSH mode:”`) and continues instead of returning an error. This ensures that builds pulling public images are not blocked by missing auth credentials.
- Push Mode Behavior: In push mode, the function behaves as before, errors in fetching the token or setting up Docker auth are returned, halting the build.
- Managed Auth Check: If managed authentication isn’t supported (i.e., when clientId is not provided), an error is returned unless in `NO_PUSH` mode, in which case it returns …

feat: [CI-16392]: Authenticate And Pull Private Base Images when NO_PUSH is enabled

---

cmd/kaniko-ecr/main.go

Fixed an issue with the push-only operation where ECR credentials were being incorrectly used, causing "invalid security token" errors.
Changes:
- Modified setDockerAuth to return ECR credentials for reuse in Crane operations
- Eliminated redundant authentication code in handlePushOnly
- Improved error handling for all authentication flows
- Added better comments to clarify different auth code paths
Testing: [LINK](https://app.harness.io/ng/account/gCoPSwHxS7ipOgx2iA9tOQ/all/orgs/Ansibler/projects/Automate/pipelines/opecrpushonly/executions/MZcc7pZATHWhEkVdZuKoAQ/pipeline?storeType=INLINE)

feat: [CI-17122]: ECR auth for push-only operation + code refactoring

---

docker/acr/Dockerfile.linux.amd64
docker/acr/Dockerfile.linux.arm64
docker/docker/Dockerfile.linux.amd64
docker/docker/Dockerfile.linux.arm64
docker/ecr/Dockerfile.linux.amd64
docker/ecr/Dockerfile.linux.arm64
docker/gar/Dockerfile.linux.amd64
docker/gar/Dockerfile.linux.arm64

Updated our kaniko-executor images to use Chainguard's maintained fork of Kaniko since Google has archived the original project. This ensures continued support and security updates for our drone-kaniko-plugins.
- Replaced Google's kaniko images with builds from Chainguard's maintained fork
- Updated Docker build configurations for all supported platforms (amd64/arm64)
- Applied changes across all registry types (ACR, Docker Hub, ECR)
Google has archived the Kaniko project, making Chainguard's fork the most actively maintained option for continued use and security updates.

feat: [CI-18100]: Switch to Chainguard-maintained Kaniko images after Google archival

---

README.md
cmd/kaniko-acr/main.go
cmd/kaniko-acr/main_test.go
cmd/kaniko-docker/main.go
cmd/kaniko-docker/main_test.go
cmd/kaniko-ecr/main.go
cmd/kaniko-gar/main.go
cmd/kaniko-gar/main_test.go
cmd/kaniko-gcr/main.go
cmd/kaniko-gcr/main_test.go
pkg/utils/custom_string_slice.go

It adds enhanced build arguments support with CustomStringSliceFlag for flexible multi-argument handling across all registry implementations while maintaining full backward compatibility.
**Key Features:**
Semicolon Delimiter: Use PLUGIN_BUILD_ARGS_NEW="ARG1=value1;ARG2=value2;ARG3=value3" for multiple build arguments
Comma Support: Enable PLUGIN_MULTIPLE_BUILD_ARGS=true for build args containing commas
Universal Implementation: Consistent syntax across all registry plugins (Docker, GCR, ECR, ACR, GAR)
CLI Integration: Seamless urfave/cli framework integration with type-safe parsing
**New Inputs:**
PLUGIN_BUILD_ARGS_NEW: Semicolon-delimited build arguments string
PLUGIN_MULTIPLE_BUILD_ARGS: Boolean flag for comma-containing argument values
**Backward Compatibility:**
✅ All existing --args …

fix: [CI-18923]: Build argument getting split if it has a comma in the value
